<?php

namespace ContainerArO9vQx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PdykhYjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pdykhYj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pdykhYj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fanRepository' => ['privates', 'App\\Repository\\FanRepository', 'getFanRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'fanRepository' => 'App\\Repository\\FanRepository',
            'serializer' => '?',
        ]);
    }
}
