<?php

namespace ContainerVc6y1xi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fmm_APOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fmm.APO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fmm.APO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fanRepository' => ['privates', 'App\\Repository\\FanRepository', 'getFanRepositoryService', true],
            'fanRevenueRepository' => ['privates', 'App\\Repository\\FanRevenueRepository', 'getFanRevenueRepositoryService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'fanRepository' => 'App\\Repository\\FanRepository',
            'fanRevenueRepository' => 'App\\Repository\\FanRevenueRepository',
            'serializer' => '?',
        ]);
    }
}
