<?php

namespace ContainerVc6y1xi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_DefaultEntityManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'doctrine.orm.default_entity_manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['doctrine.orm.default_entity_manager'] = $container->createProxy('EntityManagerGhostEbeb667', static fn () => \EntityManagerGhostEbeb667::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Proxy/Autoloader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/cache/src/CacheItemPoolInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/cache/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/cache-contracts/CacheInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/log/src/LoggerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/cache/ResettableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/log/src/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/cache/Adapter/ArrayAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Mapping/MappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/MappingDriverChain.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/NamingStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/UnderscoreNamingStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/QuoteStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Internal/SQLResultCasing.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/DefaultQuoteStrategy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/TypedFieldMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/DefaultTypedFieldMapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Repository/RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/RepositoryFactoryCompatibility.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ContainerRepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/ManagerConfigurator.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/Mapping/Driver/ColocatedMappingDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/ReflectionBasedDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/Mapping/Driver/AttributeDriver.php';

        $a = new \Doctrine\ORM\Configuration();

        $b = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
        $b->addDriver(($container->privates['doctrine.orm.default_attribute_metadata_driver'] ??= new \Doctrine\ORM\Mapping\Driver\AttributeDriver([(\dirname(__DIR__, 4).'/src/Entity')], true)), 'App\\Entity');

        $a->setEntityNamespaces(['App' => 'App\\Entity']);
        $a->setMetadataCache(new \Symfony\Component\Cache\Adapter\ArrayAdapter());
        $a->setQueryCache(($container->privates['cache.doctrine.orm.default.query'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $a->setResultCache(($container->privates['cache.doctrine.orm.default.result'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
        $a->setMetadataDriverImpl(new \Doctrine\Bundle\DoctrineBundle\Mapping\MappingDriver($b, new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine.ulid_generator' => ['privates', 'doctrine.ulid_generator', 'getDoctrine_UlidGeneratorService', true],
            'doctrine.uuid_generator' => ['privates', 'doctrine.uuid_generator', 'getDoctrine_UuidGeneratorService', true],
        ], [
            'doctrine.ulid_generator' => '?',
            'doctrine.uuid_generator' => '?',
        ])));
        $a->setProxyDir(($container->targetDir.''.'/doctrine/orm/Proxies'));
        $a->setProxyNamespace('Proxies');
        $a->setAutoGenerateProxyClasses(true);
        $a->setSchemaIgnoreClasses([]);
        $a->setClassMetadataFactoryName('Doctrine\\Bundle\\DoctrineBundle\\Mapping\\ClassMetadataFactory');
        $a->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
        $a->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy(0, true));
        $a->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
        $a->setTypedFieldMapper(new \Doctrine\ORM\Mapping\DefaultTypedFieldMapper());
        $a->setEntityListenerResolver(($container->services['doctrine.orm.default_entity_listener_resolver'] ?? $container->load('getDoctrine_Orm_DefaultEntityListenerResolverService')));
        $a->setLazyGhostObjectEnabled(true);
        $a->setIdentityGenerationPreferences([]);
        $a->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Repository\\AnalysesRepository' => ['privates', 'App\\Repository\\AnalysesRepository', 'getAnalysesRepositoryService', true],
            'App\\Repository\\ContratEntraineurRepository' => ['privates', 'App\\Repository\\ContratEntraineurRepository', 'getContratEntraineurRepositoryService', true],
            'App\\Repository\\ContratJoueurRepository' => ['privates', 'App\\Repository\\ContratJoueurRepository', 'getContratJoueurRepositoryService', true],
            'App\\Repository\\ContratKineRepository' => ['privates', 'App\\Repository\\ContratKineRepository', 'getContratKineRepositoryService', true],
            'App\\Repository\\ContratMedecinRepository' => ['privates', 'App\\Repository\\ContratMedecinRepository', 'getContratMedecinRepositoryService', true],
            'App\\Repository\\ContratPhotographeRepository' => ['privates', 'App\\Repository\\ContratPhotographeRepository', 'getContratPhotographeRepositoryService', true],
            'App\\Repository\\ContratPresidentRepository' => ['privates', 'App\\Repository\\ContratPresidentRepository', 'getContratPresidentRepositoryService', true],
            'App\\Repository\\EntraineurRepository' => ['privates', 'App\\Repository\\EntraineurRepository', 'getEntraineurRepositoryService', true],
            'App\\Repository\\EquipeRepository' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
            'App\\Repository\\EquipesAdversairesRepository' => ['privates', 'App\\Repository\\EquipesAdversairesRepository', 'getEquipesAdversairesRepositoryService', true],
            'App\\Repository\\FanRepository' => ['privates', 'App\\Repository\\FanRepository', 'getFanRepositoryService', true],
            'App\\Repository\\FanRevenueRepository' => ['privates', 'App\\Repository\\FanRevenueRepository', 'getFanRevenueRepositoryService', true],
            'App\\Repository\\JoueurRepository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
            'App\\Repository\\KineRepository' => ['privates', 'App\\Repository\\KineRepository', 'getKineRepositoryService', true],
            'App\\Repository\\LogisticRepository' => ['privates', 'App\\Repository\\LogisticRepository', 'getLogisticRepositoryService', true],
            'App\\Repository\\MatchsRepository' => ['privates', 'App\\Repository\\MatchsRepository', 'getMatchsRepositoryService', true],
            'App\\Repository\\MedecinRepository' => ['privates', 'App\\Repository\\MedecinRepository', 'getMedecinRepositoryService', true],
            'App\\Repository\\MedicalCostRepository' => ['privates', 'App\\Repository\\MedicalCostRepository', 'getMedicalCostRepositoryService', true],
            'App\\Repository\\PhotographeRepository' => ['privates', 'App\\Repository\\PhotographeRepository', 'getPhotographeRepositoryService', true],
            'App\\Repository\\PresidentRepository' => ['privates', 'App\\Repository\\PresidentRepository', 'getPresidentRepositoryService', true],
            'App\\Repository\\SponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
            'App\\Repository\\SponsorRevenueRepository' => ['privates', 'App\\Repository\\SponsorRevenueRepository', 'getSponsorRevenueRepositoryService', true],
            'App\\Repository\\TalentDataBaseRepository' => ['privates', 'App\\Repository\\TalentDataBaseRepository', 'getTalentDataBaseRepositoryService', true],
            'App\\Repository\\TaskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'App\\Repository\\TicketRepository' => ['privates', 'App\\Repository\\TicketRepository', 'getTicketRepositoryService', true],
            'App\\Repository\\TrainingsessionRepository' => ['privates', 'App\\Repository\\TrainingsessionRepository', 'getTrainingsessionRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'App\\Repository\\AnalysesRepository' => '?',
            'App\\Repository\\ContratEntraineurRepository' => '?',
            'App\\Repository\\ContratJoueurRepository' => '?',
            'App\\Repository\\ContratKineRepository' => '?',
            'App\\Repository\\ContratMedecinRepository' => '?',
            'App\\Repository\\ContratPhotographeRepository' => '?',
            'App\\Repository\\ContratPresidentRepository' => '?',
            'App\\Repository\\EntraineurRepository' => '?',
            'App\\Repository\\EquipeRepository' => '?',
            'App\\Repository\\EquipesAdversairesRepository' => '?',
            'App\\Repository\\FanRepository' => '?',
            'App\\Repository\\FanRevenueRepository' => '?',
            'App\\Repository\\JoueurRepository' => '?',
            'App\\Repository\\KineRepository' => '?',
            'App\\Repository\\LogisticRepository' => '?',
            'App\\Repository\\MatchsRepository' => '?',
            'App\\Repository\\MedecinRepository' => '?',
            'App\\Repository\\MedicalCostRepository' => '?',
            'App\\Repository\\PhotographeRepository' => '?',
            'App\\Repository\\PresidentRepository' => '?',
            'App\\Repository\\SponsorRepository' => '?',
            'App\\Repository\\SponsorRevenueRepository' => '?',
            'App\\Repository\\TalentDataBaseRepository' => '?',
            'App\\Repository\\TaskRepository' => '?',
            'App\\Repository\\TicketRepository' => '?',
            'App\\Repository\\TrainingsessionRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
        ])));

        $instance = ($lazyLoad->__construct(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')), $a, ($container->privates['doctrine.dbal.default_connection.event_manager'] ?? $container->load('getDoctrine_Dbal_DefaultConnection_EventManagerService'))) && false ?: $lazyLoad);

        (new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator([], []))->configure($instance);

        return $instance;
    }
}
