<?php

namespace ContainerVc6y1xi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPresidentListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\PresidentListener' shared autowired service.
     *
     * @return \App\EventListener\PresidentListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/PresidentListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\EventListener\\PresidentListener'])) {
            return $container->privates['App\\EventListener\\PresidentListener'];
        }

        return $container->privates['App\\EventListener\\PresidentListener'] = new \App\EventListener\PresidentListener($a);
    }
}
