<?php

namespace Container8jpj8Yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJoueurListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\JoueurListener' shared autowired service.
     *
     * @return \App\EventListener\JoueurListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/JoueurListener.php';

        return $container->privates['App\\EventListener\\JoueurListener'] = new \App\EventListener\JoueurListener();
    }
}
