<?php

namespace Container8jpj8Yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_UnionHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'jms_serializer.union_handler' shared service.
     *
     * @return \JMS\Serializer\Handler\UnionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Handler/SubscribingHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Handler/UnionHandler.php';

        return $container->privates['jms_serializer.union_handler'] = new \JMS\Serializer\Handler\UnionHandler();
    }
}
