<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'entraineur' => [parent::class, 'entraineur', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueur' => [parent::class, 'joueur', null],
        "\0".parent::class."\0".'medecin' => [parent::class, 'medecin', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'photographe' => [parent::class, 'photographe', null],
        "\0".parent::class."\0".'president' => [parent::class, 'president', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'email' => [parent::class, 'email', null],
        'entraineur' => [parent::class, 'entraineur', null],
        'id' => [parent::class, 'id', null],
        'joueur' => [parent::class, 'joueur', null],
        'medecin' => [parent::class, 'medecin', null],
        'password' => [parent::class, 'password', null],
        'photographe' => [parent::class, 'photographe', null],
        'president' => [parent::class, 'president', null],
        'roles' => [parent::class, 'roles', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
