<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipe extends \App\Entity\Equipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_fondation' => [parent::class, 'date_fondation', null],
        "\0".parent::class."\0".'entraineurs' => [parent::class, 'entraineurs', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueurs' => [parent::class, 'joueurs', null],
        "\0".parent::class."\0".'kines' => [parent::class, 'kines', null],
        "\0".parent::class."\0".'medecins' => [parent::class, 'medecins', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'photographes' => [parent::class, 'photographes', null],
        "\0".parent::class."\0".'president' => [parent::class, 'president', null],
        'date_fondation' => [parent::class, 'date_fondation', null],
        'entraineurs' => [parent::class, 'entraineurs', null],
        'id' => [parent::class, 'id', null],
        'joueurs' => [parent::class, 'joueurs', null],
        'kines' => [parent::class, 'kines', null],
        'medecins' => [parent::class, 'medecins', null],
        'nom' => [parent::class, 'nom', null],
        'photographes' => [parent::class, 'photographes', null],
        'president' => [parent::class, 'president', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
