<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matchs extends \App\Entity\Matchs implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'equipeAdverse' => [parent::class, 'equipeAdverse', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'joueurs' => [parent::class, 'joueurs', null],
        "\0".parent::class."\0".'logistiques' => [parent::class, 'logistiques', null],
        "\0".parent::class."\0".'tactique' => [parent::class, 'tactique', null],
        "\0".parent::class."\0".'terrain' => [parent::class, 'terrain', null],
        "\0".parent::class."\0".'tickets' => [parent::class, 'tickets', null],
        'date' => [parent::class, 'date', null],
        'equipeAdverse' => [parent::class, 'equipeAdverse', null],
        'id' => [parent::class, 'id', null],
        'joueurs' => [parent::class, 'joueurs', null],
        'logistiques' => [parent::class, 'logistiques', null],
        'tactique' => [parent::class, 'tactique', null],
        'terrain' => [parent::class, 'terrain', null],
        'tickets' => [parent::class, 'tickets', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
