<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fan extends \App\Entity\Fan implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'datedeb' => [parent::class, 'datedeb', null],
        "\0".parent::class."\0".'datefin' => [parent::class, 'datefin', null],
        "\0".parent::class."\0".'fan_revenue' => [parent::class, 'fan_revenue', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'numero_telephone' => [parent::class, 'numero_telephone', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'service_fourni' => [parent::class, 'service_fourni', null],
        'datedeb' => [parent::class, 'datedeb', null],
        'datefin' => [parent::class, 'datefin', null],
        'fan_revenue' => [parent::class, 'fan_revenue', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'lastname' => [parent::class, 'lastname', null],
        'numero_telephone' => [parent::class, 'numero_telephone', null],
        'prix' => [parent::class, 'prix', null],
        'service_fourni' => [parent::class, 'service_fourni', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
