<?php

namespace Container8PNbSrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedecinListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\MedecinListener' shared autowired service.
     *
     * @return \App\EventListener\MedecinListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/MedecinListener.php';

        return $container->privates['App\\EventListener\\MedecinListener'] = new \App\EventListener\MedecinListener();
    }
}
