<?php

namespace ContainerCMwDxd0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntraineurListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\EntraineurListener' shared autowired service.
     *
     * @return \App\EventListener\EntraineurListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/EntraineurListener.php';

        return $container->privates['App\\EventListener\\EntraineurListener'] = new \App\EventListener\EntraineurListener();
    }
}
