<?php

namespace Container2wyPAyo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CjJGr32Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cjJGr32' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cjJGr32'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'equipeRepository' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'talentRepo' => ['privates', 'App\\Repository\\TalentDataBaseRepository', 'getTalentDataBaseRepositoryService', true],
        ], [
            'entityManager' => '?',
            'equipeRepository' => 'App\\Repository\\EquipeRepository',
            'passwordHasher' => '?',
            'talentRepo' => 'App\\Repository\\TalentDataBaseRepository',
        ]);
    }
}
