<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCMwDxd0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCMwDxd0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCMwDxd0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCMwDxd0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCMwDxd0\App_KernelDevDebugContainer([
    'container.build_hash' => 'CMwDxd0',
    'container.build_id' => '1054a057',
    'container.build_time' => 1740066361,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCMwDxd0');
