<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jpj8Yz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jpj8Yz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8jpj8Yz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8jpj8Yz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8jpj8Yz\App_KernelDevDebugContainer([
    'container.build_hash' => '8jpj8Yz',
    'container.build_id' => 'cc7374e5',
    'container.build_time' => 1740598011,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jpj8Yz');
