<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgl59KB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgl59KB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTgl59KB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTgl59KB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTgl59KB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tgl59KB',
    'container.build_id' => 'a6c3023f',
    'container.build_time' => 1741535875,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgl59KB');
